### ISSUE TITLE
Feature: User can send requests to other users 

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/Final-Project-OverLook#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send requests to other users

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allows a manager user to send a request form to an employee user. Having a one way street of form information 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121650766/231606290-d7ccd66e-cbb3-471f-8cdd-025ba88eef55.png)
![image](https://user-images.githubusercontent.com/121650766/231606313-a9a1788c-5c6e-4bd5-8882-61c093f87f7f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Add users to manger accounts and link their information to the employee acocunt
- [x] be able to pull information from the manger account to other user

### ☁️ Server Tasks

- [x] set server to take form request and send to the database
- [x] set server to also create different accounts based upon database information 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to hold the form portion 
- [x] create a component to save the home screen 
- [x] create a component to create pull out menu for the user 

### 🧑‍⚕️ Clean Up Tasks

- [x] clean up database and make sure their are 2 set account in there at all times.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
