### ISSUE TITLE
Feature: User can edit request and view other members accounts

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/Final-Project-OverLook#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit request and view other members accounts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Requests can  be edited after they are created and other employee user accounts can be viewed in a grid format
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121650766/231655185-97f9f7f6-345c-4563-811c-0298bc4d4341.png)
![image](https://user-images.githubusercontent.com/121650766/231655123-b5eba048-fbb6-4795-811d-3bfcfa3f1bc6.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to  view proper data
- [x] Update `data.sql` to  view the proper data when clicked 

### ☁️ Server Tasks

- [x] Update `server/index.js` to  create a post portion of the server
- [x] make a portion of new code that allows the suer to change information
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to update the tasks 
- [x] create a new view to hold all the tasks inside

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
