### ISSUE TITLE
User can delete any types of requests made 

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/Final-Project-OverLook#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User is able to navigate through requests and either edit or delete the request with a specific modal popping up for the deletion of the request

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will click the x next to the request and a modal will pop up making sure it wants to be deleted. then the request will be deleted. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121650766/234496480-f85a82a4-fc27-4b33-9f29-16ec2a5c8d4f.png)
![image](https://user-images.githubusercontent.com/121650766/234496524-1eef1634-439d-41a2-81a6-8e6e00ba74fc.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...
- [ ] Add new sql function to remove items from pgweb

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client
- [ ] add new function to handle all delete functions in conjunction with the sql feature

### ⚡ Client Tasks

- [ ] Create a component to add a delete button ontop of the existing edit requests
- [ ] Create a modal component to make sure the item is wanting to be deleted
- [ ] have that modal send request for the requestId to delete the item

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
