### ISSUE TITLE
User can sort and view each item after they are submitted

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/Final-Project-OverLook#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

feature will allow user to check items when they are submitted or if they are submitted 
also allow the user to check each individual when the submit the item
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121650766/235855404-6fbbb957-737c-4e7e-a34c-31af1a06ea6f.png)
![image](https://user-images.githubusercontent.com/121650766/235855475-631488e1-4d39-4ebe-a01d-a192f04532d9.png)
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql`  to add extra items to check if the form is compelete or incompete
- [ ] Update `data.sql` to  match each of the items that were changed

### ☁️ Server Tasks

- [ ] Update `server/index.js` to pull all data with a singular api call 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to view all the tasks 
- [ ] create an additional component to show as a modal when a button is clicked showing additional information 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
